/* AnalisadorTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. AnalisadorTokenManager.java */
package compilador.analisadorsintatico;
import java.io.*;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.lang.reflect.*;
import compilador.recovery.*;
import compilador.semantico.*;
import compilador.programa.Controller;

/** Token Manager. */
@SuppressWarnings ("unused")
public class AnalisadorTokenManager implements AnalisadorConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 9:
         jjmatchedKind = 58;
         return jjMoveNfa_0(0, 0);
      case 10:
         jjmatchedKind = 54;
         return jjMoveNfa_0(0, 0);
      case 12:
         jjmatchedKind = 57;
         return jjMoveNfa_0(0, 0);
      case 13:
         jjmatchedKind = 55;
         return jjMoveStringLiteralDfa1_0(0x100000000000000L);
      case 32:
         jjmatchedKind = 53;
         return jjMoveNfa_0(0, 0);
      case 33:
         jjmatchedKind = 51;
         return jjMoveStringLiteralDfa1_0(0x100000000000L);
      case 37:
         jjmatchedKind = 41;
         return jjMoveStringLiteralDfa1_0(0x40000000000L);
      case 38:
         jjmatchedKind = 49;
         return jjMoveNfa_0(0, 0);
      case 40:
         jjmatchedKind = 34;
         return jjMoveNfa_0(0, 0);
      case 41:
         jjmatchedKind = 35;
         return jjMoveNfa_0(0, 0);
      case 42:
         jjmatchedKind = 39;
         return jjMoveStringLiteralDfa1_0(0x10000000000L);
      case 43:
         jjmatchedKind = 36;
         return jjMoveNfa_0(0, 0);
      case 44:
         jjmatchedKind = 29;
         return jjMoveNfa_0(0, 0);
      case 45:
         jjmatchedKind = 37;
         return jjMoveNfa_0(0, 0);
      case 46:
         jjmatchedKind = 28;
         return jjMoveNfa_0(0, 0);
      case 47:
         jjmatchedKind = 38;
         return jjMoveStringLiteralDfa1_0(0x1800000000000000L);
      case 58:
         return jjMoveStringLiteralDfa1_0(0x10000000000000L);
      case 60:
         jjmatchedKind = 45;
         return jjMoveStringLiteralDfa1_0(0x800000000000L);
      case 61:
         return jjMoveStringLiteralDfa1_0(0x80000000000L);
      case 62:
         jjmatchedKind = 46;
         return jjMoveStringLiteralDfa1_0(0x1000000000000L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x200L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x100L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x20004L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x400L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x80000L);
      case 71:
         return jjMoveStringLiteralDfa1_0(0x2000L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x20L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x48L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x4002L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x41000L);
      case 86:
         return jjMoveStringLiteralDfa1_0(0x100010L);
      case 87:
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 91:
         jjmatchedKind = 32;
         return jjMoveNfa_0(0, 0);
      case 93:
         jjmatchedKind = 33;
         return jjMoveNfa_0(0, 0);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x200L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x100L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x20004L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x400L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x80000L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x2000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x20L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x48L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x4002L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x41000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x100010L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 123:
         jjmatchedKind = 30;
         return jjMoveNfa_0(0, 0);
      case 124:
         jjmatchedKind = 50;
         return jjMoveNfa_0(0, 0);
      case 125:
         jjmatchedKind = 31;
         return jjMoveNfa_0(0, 0);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 0);
   }
   switch(curChar)
   {
      case 10:
         if ((active0 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 1;
         }
         break;
      case 37:
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 1;
         }
         break;
      case 42:
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x1000000000000000L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 1;
         }
         break;
      case 45:
         if ((active0 & 0x10000000000000L) != 0L)
         {
            jjmatchedKind = 52;
            jjmatchedPos = 1;
         }
         break;
      case 47:
         if ((active0 & 0x800000000000000L) != 0L)
         {
            jjmatchedKind = 59;
            jjmatchedPos = 1;
         }
         break;
      case 61:
         if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 1;
         }
         break;
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x80050L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x102884L);
      case 72:
         return jjMoveStringLiteralDfa2_0(active0, 0x10100L);
      case 79:
         if ((active0 & 0x1000L) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x8208L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x40002L);
      case 83:
         if ((active0 & 0x20L) != 0L)
         {
            jjmatchedKind = 5;
            jjmatchedPos = 1;
         }
         break;
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000L);
      case 88:
         return jjMoveStringLiteralDfa2_0(active0, 0x400L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x80050L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x102884L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x10100L);
      case 111:
         if ((active0 & 0x1000L) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x8208L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x40002L);
      case 115:
         if ((active0 & 0x20L) != 0L)
         {
            jjmatchedKind = 5;
            jjmatchedPos = 1;
         }
         break;
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x400L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 1);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x180L);
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x400L);
      case 70:
         return jjMoveStringLiteralDfa3_0(active0, 0x4L);
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x8202L);
      case 82:
         return jjMoveStringLiteralDfa3_0(active0, 0x100010L);
      case 84:
         if ((active0 & 0x8L) != 0L)
         {
            jjmatchedKind = 3;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x800L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 85:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x180L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x400L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x4L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x8202L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x100010L);
      case 116:
         if ((active0 & 0x8L) != 0L)
         {
            jjmatchedKind = 3;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x800L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 2);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 2);
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa4_0(active0, 0x400L);
      case 69:
         if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 3;
         }
         break;
      case 71:
         return jjMoveStringLiteralDfa4_0(active0, 0x2L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x100014L);
      case 76:
         if ((active0 & 0x80L) != 0L)
         {
            jjmatchedKind = 7;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x10200L);
      case 80:
         if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 15;
            jjmatchedPos = 3;
         }
         break;
      case 82:
         if ((active0 & 0x100L) != 0L)
         {
            jjmatchedKind = 8;
            jjmatchedPos = 3;
         }
         break;
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000L);
      case 85:
         return jjMoveStringLiteralDfa4_0(active0, 0x40L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x400L);
      case 101:
         if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 3;
         }
         break;
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x2L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x100014L);
      case 108:
         if ((active0 & 0x80L) != 0L)
         {
            jjmatchedKind = 7;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x10200L);
      case 112:
         if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 15;
            jjmatchedPos = 3;
         }
         break;
      case 114:
         if ((active0 & 0x100L) != 0L)
         {
            jjmatchedKind = 8;
            jjmatchedPos = 3;
         }
         break;
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x40L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 3);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 3);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 3);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0x10L);
      case 69:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x200L);
      case 70:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000L);
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0x4L);
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0x42L);
      case 85:
         return jjMoveStringLiteralDfa5_0(active0, 0x400L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x10L);
      case 101:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x200L);
      case 102:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x4L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x42L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x400L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 4);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 4);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 4);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa6_0(active0, 0x242L);
      case 66:
         return jjMoveStringLiteralDfa6_0(active0, 0x10L);
      case 69:
         if ((active0 & 0x4L) != 0L)
         {
            jjmatchedKind = 2;
            jjmatchedPos = 5;
         }
         break;
      case 84:
         return jjMoveStringLiteralDfa6_0(active0, 0x400L);
      case 89:
         if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 5;
         }
         break;
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x242L);
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x10L);
      case 101:
         if ((active0 & 0x4L) != 0L)
         {
            jjmatchedKind = 2;
            jjmatchedPos = 5;
         }
         break;
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x400L);
      case 121:
         if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 5;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(0, 5);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 5);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 5);
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x400L) != 0L)
         {
            jjmatchedKind = 10;
            jjmatchedPos = 6;
         }
         break;
      case 76:
         if ((active0 & 0x40L) != 0L)
         {
            jjmatchedKind = 6;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x10L);
      case 77:
         if ((active0 & 0x2L) != 0L)
         {
            jjmatchedKind = 1;
            jjmatchedPos = 6;
         }
         break;
      case 78:
         if ((active0 & 0x200L) != 0L)
         {
            jjmatchedKind = 9;
            jjmatchedPos = 6;
         }
         break;
      case 101:
         if ((active0 & 0x400L) != 0L)
         {
            jjmatchedKind = 10;
            jjmatchedPos = 6;
         }
         break;
      case 108:
         if ((active0 & 0x40L) != 0L)
         {
            jjmatchedKind = 6;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x10L);
      case 109:
         if ((active0 & 0x2L) != 0L)
         {
            jjmatchedKind = 1;
            jjmatchedPos = 6;
         }
         break;
      case 110:
         if ((active0 & 0x200L) != 0L)
         {
            jjmatchedKind = 9;
            jjmatchedPos = 6;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(0, 6);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 6);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 6);
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x10L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 7;
         }
         break;
      case 101:
         if ((active0 & 0x10L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 7;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(0, 7);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int strKind = jjmatchedKind;
   int strPos = jjmatchedPos;
   int seenUpto;
   input_stream.backup(seenUpto = curPos + 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { throw new Error("Internal Error"); }
   curPos = 0;
   int startsAt = 0;
   jjnewStateCnt = 55;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 25)
                        kind = 25;
                     { jjCheckNAddStates(0, 2); }
                  }
                  else if ((0x8400000000L & l) != 0L)
                  {
                     if (kind > 67)
                        kind = 67;
                  }
                  else if (curChar == 58)
                  {
                     if (kind > 65)
                        kind = 65;
                     { jjCheckNAddStates(3, 6); }
                  }
                  else if (curChar == 61)
                     jjstateSet[jjnewStateCnt++] = 2;
                  if (curChar == 34)
                     { jjCheckNAddStates(7, 10); }
                  else if (curChar == 39)
                     { jjCheckNAddStates(11, 14); }
                  else if (curChar == 61)
                  {
                     if (kind > 66)
                        kind = 66;
                  }
                  break;
               case 1:
                  if (curChar == 61 && kind > 66)
                     kind = 66;
                  break;
               case 2:
                  if (curChar == 61)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if (curChar == 61)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 4:
                  if ((0x8400000000L & l) != 0L && kind > 67)
                     kind = 67;
                  break;
               case 5:
                  if (curChar != 58)
                     break;
                  if (kind > 65)
                     kind = 65;
                  { jjCheckNAddStates(3, 6); }
                  break;
               case 6:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(6, 7); }
                  break;
               case 7:
                  if (curChar != 45)
                     break;
                  if (kind > 65)
                     kind = 65;
                  { jjCheckNAddTwoStates(7, 8); }
                  break;
               case 8:
                  if ((0xffffff7affffffffL & l) == 0L)
                     break;
                  if (kind > 65)
                     kind = 65;
                  { jjCheckNAdd(8); }
                  break;
               case 9:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(9, 10); }
                  break;
               case 10:
                  if (curChar == 45)
                     { jjCheckNAddStates(15, 19); }
                  break;
               case 11:
                  if (curChar == 32)
                     { jjCheckNAddStates(20, 23); }
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(24, 26); }
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjAddStates(27, 29); }
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) != 0L && kind > 68)
                     kind = 68;
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 25)
                     kind = 25;
                  { jjCheckNAddStates(0, 2); }
                  break;
               case 34:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) != 0L && kind > 26)
                     kind = 26;
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(30, 33); }
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(34); }
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(38, 34); }
                  break;
               case 40:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(34, 36); }
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 25)
                     kind = 25;
                  jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) != 0L && kind > 25)
                     kind = 25;
                  break;
               case 43:
                  if (curChar == 39)
                     { jjCheckNAddStates(11, 14); }
                  break;
               case 44:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     { jjCheckNAddTwoStates(44, 45); }
                  break;
               case 45:
                  if (curChar == 39 && kind > 27)
                     kind = 27;
                  break;
               case 46:
                  if ((0xfffffffbfffffbffL & l) != 0L)
                     { jjCheckNAddTwoStates(46, 47); }
                  break;
               case 47:
                  if (curChar == 34 && kind > 67)
                     kind = 67;
                  break;
               case 48:
                  if (curChar == 34)
                     { jjCheckNAddStates(7, 10); }
                  break;
               case 49:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddTwoStates(49, 50); }
                  break;
               case 50:
                  if (curChar == 34 && kind > 27)
                     kind = 27;
                  break;
               case 51:
                  if ((0xffffff7ffffffbffL & l) != 0L)
                     { jjCheckNAddTwoStates(51, 52); }
                  break;
               case 52:
                  if (curChar == 39 && kind > 67)
                     kind = 67;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 24)
                        kind = 24;
                     { jjCheckNAddTwoStates(31, 32); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddStates(37, 42); }
                  else if (curChar == 95)
                     { jjCheckNAddStates(43, 47); }
                  break;
               case 8:
                  if (kind > 65)
                     kind = 65;
                  jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 12:
                  if ((0x7fffffe87fffffeL & l) != 0L && kind > 65)
                     kind = 65;
                  break;
               case 13:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddStates(48, 53); }
                  break;
               case 14:
                  if (curChar == 95)
                     { jjCheckNAdd(15); }
                  break;
               case 16:
                  if (curChar == 95)
                     { jjCheckNAddStates(54, 57); }
                  break;
               case 17:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAdd(15); }
                  break;
               case 18:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddStates(24, 26); }
                  break;
               case 19:
                  if ((0x7fffffe07fffffeL & l) != 0L && kind > 65)
                     kind = 65;
                  break;
               case 20:
                  if (curChar == 95 && kind > 65)
                     kind = 65;
                  break;
               case 21:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddStates(37, 42); }
                  break;
               case 22:
                  if (curChar == 95)
                     { jjCheckNAdd(23); }
                  break;
               case 24:
                  if ((0x7fffffe87fffffeL & l) != 0L && kind > 24)
                     kind = 24;
                  break;
               case 25:
                  if (curChar == 95)
                     { jjCheckNAddStates(58, 61); }
                  break;
               case 26:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAdd(23); }
                  break;
               case 27:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddStates(27, 29); }
                  break;
               case 28:
                  if ((0x7fffffe07fffffeL & l) != 0L && kind > 24)
                     kind = 24;
                  break;
               case 29:
                  if (curChar == 95 && kind > 24)
                     kind = 24;
                  break;
               case 30:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  { jjCheckNAddTwoStates(31, 32); }
                  break;
               case 31:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(31, 32); }
                  break;
               case 44:
                  { jjAddStates(62, 63); }
                  break;
               case 46:
                  { jjAddStates(64, 65); }
                  break;
               case 49:
                  { jjAddStates(66, 67); }
                  break;
               case 51:
                  { jjAddStates(68, 69); }
                  break;
               case 53:
                  if (curChar == 95)
                     { jjCheckNAddStates(43, 47); }
                  break;
               case 54:
                  if (curChar != 95)
                     break;
                  if (kind > 68)
                     kind = 68;
                  { jjCheckNAdd(54); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 8:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 65)
                     kind = 65;
                  jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 44:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(62, 63); }
                  break;
               case 46:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(64, 65); }
                  break;
               case 49:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(66, 67); }
                  break;
               case 51:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(68, 69); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 55 - (jjnewStateCnt = startsAt)))
         break;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { break; }
   }
   if (jjmatchedPos > strPos)
      return curPos;

   int toRet = Math.max(curPos, seenUpto);

   if (curPos < toRet)
      for (i = toRet - Math.min(curPos, seenUpto); i-- > 0; )
         try { curChar = input_stream.readChar(); }
         catch(java.io.IOException e) { throw new Error("Internal Error : Please send a bug report."); }

   if (jjmatchedPos < strPos)
   {
      jjmatchedKind = strKind;
      jjmatchedPos = strPos;
   }
   else if (jjmatchedPos == strPos && jjmatchedKind > strKind)
      jjmatchedKind = strKind;

   return toRet;
}
private int jjMoveStringLiteralDfa0_2(){
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_2(0x8000000000000000L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_2(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStopAtPos(1, 63);
         break;
      default :
         return 2;
   }
   return 2;
}
private int jjMoveStringLiteralDfa0_1()
{
   return jjMoveNfa_1(0, 0);
}
private int jjMoveNfa_1(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 1;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x2400L & l) != 0L)
                     kind = 61;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 1 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, "\56", "\54", "\173", "\175", "\133", "\135", "\50", "\51", "\53", "\55", 
"\57", "\52", "\52\52", "\45", "\45\45", "\75\75", "\41\75", "\74", "\76", "\74\75", 
"\76\75", "\46", "\174", "\41", "\72\55", null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   34, 37, 41, 6, 7, 9, 10, 49, 50, 51, 52, 44, 45, 46, 47, 10, 
   11, 12, 13, 16, 11, 12, 13, 16, 12, 13, 16, 24, 21, 25, 38, 34, 
   39, 40, 38, 34, 39, 22, 23, 24, 29, 21, 25, 26, 23, 27, 28, 54, 
   14, 15, 12, 20, 13, 16, 17, 15, 18, 19, 26, 23, 27, 28, 44, 45, 
   46, 47, 49, 50, 51, 52, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      TokenLexicalActions(matchedToken);
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   switch(curLexState)
   {
     case 0:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       if (jjmatchedPos == 0 && jjmatchedKind > 69)
       {
          jjmatchedKind = 69;
       }
       break;
     case 1:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       if (jjmatchedPos == 0 && jjmatchedKind > 62)
       {
          jjmatchedKind = 62;
       }
       break;
     case 2:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_2();
       if (jjmatchedPos == 0 && jjmatchedKind > 64)
       {
          jjmatchedKind = 64;
       }
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           matchedToken.specialToken = specialToken;
           TokenLexicalActions(matchedToken);
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else
        {
           if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
           {
              matchedToken = jjFillToken();
              if (specialToken == null)
                 specialToken = matchedToken;
              else
              {
                 matchedToken.specialToken = specialToken;
                 specialToken = (specialToken.next = matchedToken);
              }
              SkipLexicalActions(matchedToken);
           }
           else
              SkipLexicalActions(null);
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 65 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        Analisador.printarStatic("ERRO DE LEXEMA. Voce tentou declarar um comentario de cabecalho? \nUse :- constanteLiteral, por exemplo: :- 'meu programa' \n");
        Analisador.setHouveErroLexico();
         break;
      case 66 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                Analisador.setHouveErroLexico();
                        Analisador.printarStatic("ERRO DE LEXEMA : | " + image + " | na linha " + matchedToken.beginLine + " e na coluna " + matchedToken.beginColumn + " \nVoce tentou fazer uma atribuicao? Use ==\n");
         break;
      case 67 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        Analisador.setHouveErroLexico();
        Analisador.printarStatic("ERRO DE LEXEMA ao tentar declarar uma CONSTANTE_LITERAL na linha " + matchedToken.beginLine + " e na coluna " +
            matchedToken.beginColumn + ". \n Voce tentou declarar uma constante literal? \nLembre de iniciar e finalizar com apostrofos ou aspas na mesma linha e de repetir o mesmo simbolo no inicio e no fim.\n");
         break;
      case 68 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
            Analisador.setHouveErroLexico();
            Analisador.printarStatic("ERRO DE LEXEMA ao tentar declarar um IDENTIFICADOR na linha " + matchedToken.beginLine + " e na coluna " +
                        matchedToken.beginColumn + ". \nVoce tentou declarar um identificador? \nLembre de nao repetir dois underlines seguidos, dois numeros seguidos ou finalizar com um numero.\n");
         break;
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 0 :
      image.setLength(0);
        if(curLexState == COMENTARIODEBLOCO) {
            Analisador.printarStatic("ERRO DE LEXEMA. Voce esqueceu de fechar o comentario de bloco? Lembre-se de fechar com */");
            Analisador.setHouveErroLexico();
            curLexState = DEFAULT;
        }
         break;
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public AnalisadorTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public AnalisadorTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 55; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 3 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "COMENTARIODELINHA",
   "COMENTARIODEBLOCO",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 2, 0, -1, 0, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0x1fffffff1fffffL, 0x20L, 
};
static final long[] jjtoSkip = {
   0xffe0000000000000L, 0x1fL, 
};
static final long[] jjtoSpecial = {
   0x0L, 0x1eL, 
};
static final long[] jjtoMore = {
   0x0L, 0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[55];
    private final int[] jjstateSet = new int[2 * 55];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
