#pragma once

#include <iostream>
#include <string>

using namespace std;

/*
Constante para identificar as cercas
*/
const char CERCA = '#';
/*
Constante para identiciar um espaço vazio
*/
const char VAZIO = '\0';
/*
Constante para identificar um vírus
*/
const char VIRUS = 'X';
/*
Constante para identificar o tamanho de campo pequeno
*/
const int TAMANHO_PEQUENO = 1;
/*
Constante para identificar o tamanho de campo médio
*/
const int TAMANHO_MEDIO = 2;
/*
Constante para identificar o tamanho de campo grande
*/
const int TAMANHO_GRANDE = 3;

/*
Constante para definir a quantidade de colunas de todos os campos
*/
const int QUANTIDADE_COLUNAS = 20;

/*
Constante para definir a quantidade de linhas dos campos pequenos
*/
const int QUANTIDADE_LINHAS_PARA_MENORES = 10;

/*
Constante para definir a quantidade de linhas dos campos médios
*/
const int QUANTIDADE_LINHAS_PARA_MEDIOS = 15;

/*
Constante para definir a quantidade de linhas dos campos grandes
*/
const int QUANTIDADE_LINHAS_PARA_GRANDES = 25;
/*
Campo pequeno com os valores inciais
*/
char campoPequeno[QUANTIDADE_LINHAS_PARA_MENORES][QUANTIDADE_COLUNAS] = {
	{ CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA,CERCA, CERCA, CERCA, CERCA, CERCA,CERCA, CERCA, CERCA, CERCA, CERCA,CERCA,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA,CERCA, CERCA, CERCA, CERCA, CERCA,CERCA, CERCA, CERCA, CERCA, CERCA,CERCA,CERCA }
};

/*
Campo médio com os valores inciais
*/
char campoMedio[QUANTIDADE_LINHAS_PARA_MEDIOS][QUANTIDADE_COLUNAS] = {
	{ CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA,CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO,CERCA },
	{ CERCA, CERCA, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO,CERCA },
	{ CERCA, VAZIO, CERCA, VAZIO, CERCA, VAZIO, VAZIO, VAZIO,CERCA, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, CERCA,VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, CERCA, CERCA, CERCA, VAZIO, VAZIO,CERCA },
	{ CERCA, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, CERCA, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, CERCA, CERCA,CERCA },
	{ CERCA, VAZIO, VAZIO, CERCA, VAZIO, CERCA, VAZIO, VAZIO,CERCA, CERCA, CERCA, CERCA, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO,VAZIO, CERCA, CERCA, VAZIO, VAZIO, CERCA, CERCA, VAZIO, VAZIO, VAZIO, VAZIO,CERCA },
	{ CERCA, VAZIO, CERCA, VAZIO, CERCA, VAZIO, CERCA, VAZIO,VAZIO, CERCA, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, CERCA, CERCA, VAZIO, CERCA, VAZIO,VAZIO, CERCA, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, CERCA, VAZIO,VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,CERCA },
	{ CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA,CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA,CERCA }
};

/*
Campo grande com os valores inciais
*/
char campoGrande[QUANTIDADE_LINHAS_PARA_GRANDES][QUANTIDADE_COLUNAS] = {
	{ CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA,CERCA,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, CERCA, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, CERCA, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, CERCA, VAZIO, CERCA, VAZIO, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA,VAZIO,CERCA },
	{ CERCA, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,CERCA,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,CERCA,CERCA },
	{ CERCA, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, CERCA, CERCA, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, CERCA, CERCA, CERCA, VAZIO, CERCA, CERCA, CERCA, CERCA, VAZIO, CERCA, VAZIO, CERCA, CERCA, CERCA, CERCA, VAZIO, CERCA,CERCA,CERCA },
	{ CERCA, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, CERCA, CERCA, CERCA, CERCA, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, CERCA, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, CERCA, VAZIO, CERCA,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, CERCA, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, CERCA, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, CERCA, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, VAZIO, CERCA, VAZIO, VAZIO,VAZIO,CERCA },
	{ CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA, CERCA,CERCA,CERCA }
};

/*
Função para escrever os valores contidos em um campo, deve ser utilizado para exibir o campo para o usuário
*/
void escreverCampo(char campo[][QUANTIDADE_COLUNAS], int tamanhoCampo)
{
	for (int linha = 0; linha < tamanhoCampo; linha++)
	{
		for (int coluna = 0; coluna < QUANTIDADE_COLUNAS; coluna++)
			cout << campo[linha][coluna] << "";
		cout << endl;
	}
}

/*
Função para escrever os valores de um dos campos, de acordo com o parâmetro
Utilize as constantes de TAMANHO na biblioteca para selecionar o campo que deve ser escrito
*/
void escreverUmDosCampos(int tamanho)
{
	switch (tamanho)
	{
	case TAMANHO_PEQUENO:
		escreverCampo(campoPequeno, QUANTIDADE_LINHAS_PARA_MENORES);
		break;
	case TAMANHO_MEDIO:
		escreverCampo(campoMedio, QUANTIDADE_LINHAS_PARA_MEDIOS);
		break;
	case TAMANHO_GRANDE:
		escreverCampo(campoGrande, QUANTIDADE_LINHAS_PARA_GRANDES);
		break;
	}
}